export const ACTION_SET_CURRENT_USER = 'actionGetCurrentUser'
export const SET_CURRENT_USER = 'setCurrentUser'
export const ACTION_SET_PROFILE = 'actionSetProfile'

export const ACTION_GET_USERS = 'actionGetUsers'
export const SET_USERS = 'setUsers'
export const CLEAR_USERS = 'clearUsers'
export const ACTION_ADD_USER = 'actionAddUser'
export const ACTION_UPDATE_USER = 'actionUpdateUser'
export const ACTION_DELETE_USER = 'actionDeleteUser'
export const UPDATE_USER = 'updateUser'
export const ADD_USER = 'addUser'
export const DELETE_USER = 'deleteUser'

export const ACTION_GET_ENTRIES = 'actionGetEntries'
export const SET_ENTRIES = 'setEntries'
export const CLEAR_ENTRIES = 'clearEntries'
export const ACTION_ADD_ENTRY = 'actionAddEntry'
export const ACTION_UPDATE_ENTRY = 'actionUpdateEntry'
export const ACTION_DELETE_ENTRY = 'actionDeleteEntry'
export const UPDATE_ENTRY = 'updateEntry'
export const ADD_ENTRY = 'addEntry'
export const DELETE_ENTRY = 'deleteEntry'
export const ACTION_GET_REPORT = 'actionGetReport'
export const SET_REPORT = 'setReport'
export const CLEAR_REPORT = 'clearReport'


export const ACTION_UPDATE_PROFILE = 'actionUpdateUserProfile'
